# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.11 Python SDK

    Pure Storage FlashBlade REST 1.11 Python SDK. Compatible with REST API versions 1.0 - 1.11. Developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.11
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LifecycleRulePatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

#BEGIN_CUSTOM
    # IR-51527: Prevent Pytest from attempting to collect this class based on name.
    __test__ = False
#END_CUSTOM

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'keep_previous_version_for': 'int',
        'prefix': 'str'
    }

    attribute_map = {
        'enabled': 'enabled',
        'keep_previous_version_for': 'keep_previous_version_for',
        'prefix': 'prefix'
    }

    def __init__(self, enabled=None, keep_previous_version_for=None, prefix=None):  # noqa: E501
        """LifecycleRulePatch - a model defined in Swagger"""  # noqa: E501

        self._enabled = None
        self._keep_previous_version_for = None
        self._prefix = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if keep_previous_version_for is not None:
            self.keep_previous_version_for = keep_previous_version_for
        if prefix is not None:
            self.prefix = prefix

    @property
    def enabled(self):
        """Gets the enabled of this LifecycleRulePatch.  # noqa: E501

        If set to `true`, this rule will be enabled.  # noqa: E501

        :return: The enabled of this LifecycleRulePatch.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this LifecycleRulePatch.

        If set to `true`, this rule will be enabled.  # noqa: E501

        :param enabled: The enabled of this LifecycleRulePatch.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def keep_previous_version_for(self):
        """Gets the keep_previous_version_for of this LifecycleRulePatch.  # noqa: E501

        Time after which previous versions will be marked expired. Measured in milliseconds. Must be a multiple of 86400000 to represent a whole number of days.  # noqa: E501

        :return: The keep_previous_version_for of this LifecycleRulePatch.  # noqa: E501
        :rtype: int
        """
        return self._keep_previous_version_for

    @keep_previous_version_for.setter
    def keep_previous_version_for(self, keep_previous_version_for):
        """Sets the keep_previous_version_for of this LifecycleRulePatch.

        Time after which previous versions will be marked expired. Measured in milliseconds. Must be a multiple of 86400000 to represent a whole number of days.  # noqa: E501

        :param keep_previous_version_for: The keep_previous_version_for of this LifecycleRulePatch.  # noqa: E501
        :type: int
        """

        self._keep_previous_version_for = keep_previous_version_for

    @property
    def prefix(self):
        """Gets the prefix of this LifecycleRulePatch.  # noqa: E501

        Object key prefix identifying one or more objects in the bucket. Can have a maximum length of 1024 characters.  # noqa: E501

        :return: The prefix of this LifecycleRulePatch.  # noqa: E501
        :rtype: str
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix):
        """Sets the prefix of this LifecycleRulePatch.

        Object key prefix identifying one or more objects in the bucket. Can have a maximum length of 1024 characters.  # noqa: E501

        :param prefix: The prefix of this LifecycleRulePatch.  # noqa: E501
        :type: str
        """

        self._prefix = prefix

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LifecycleRulePatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LifecycleRulePatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
