# coding: utf-8

"""
    Pure Storage FlashBlade REST 1.11 Python SDK

    Pure Storage FlashBlade REST 1.11 Python SDK, developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.11
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ObjectStoreAccessKeyPost(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'Reference',
        'secret_access_key': 'str'
    }

    attribute_map = {
        'user': 'user',
        'secret_access_key': 'secret_access_key'
    }

    def __init__(self, user=None, secret_access_key=None):
        """
        ObjectStoreAccessKeyPost - a model defined in Swagger
        """

        self._user = None
        self._secret_access_key = None

        if user is not None:
          self.user = user
        if secret_access_key is not None:
          self.secret_access_key = secret_access_key

    @property
    def user(self):
        """
        Gets the user of this ObjectStoreAccessKeyPost.
        Reference of the associated user.

        :return: The user of this ObjectStoreAccessKeyPost.
        :rtype: Reference
        """
        return self._user

    @user.setter
    def user(self, user):
        """
        Sets the user of this ObjectStoreAccessKeyPost.
        Reference of the associated user.

        :param user: The user of this ObjectStoreAccessKeyPost.
        :type: Reference
        """

        self._user = user

    @property
    def secret_access_key(self):
        """
        Gets the secret_access_key of this ObjectStoreAccessKeyPost.
        The secret access key to import from another FlashBlade. To import a set of credentials, this field must be specified with the `names` query parameter. If both of these not specified, the system will generate a new set of credentials.

        :return: The secret_access_key of this ObjectStoreAccessKeyPost.
        :rtype: str
        """
        return self._secret_access_key

    @secret_access_key.setter
    def secret_access_key(self, secret_access_key):
        """
        Sets the secret_access_key of this ObjectStoreAccessKeyPost.
        The secret access key to import from another FlashBlade. To import a set of credentials, this field must be specified with the `names` query parameter. If both of these not specified, the system will generate a new set of credentials.

        :param secret_access_key: The secret_access_key of this ObjectStoreAccessKeyPost.
        :type: str
        """

        self._secret_access_key = secret_access_key

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ObjectStoreAccessKeyPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
